name: Test branches

on:
  pull_request:
    branches:
      - master

jobs:
  run-unit-tests:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      JAVA_OPTS: -Xmx3200m
      TERM: dumb
    strategy:
      fail-fast: false
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-dependencies
      with:
        path: ~/.gradle/caches
        key: build-cache-${{ hashFiles('build.gradle') }}
        restore-keys: |
          build-cache-
          build-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Resolve dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: ./gradlew dependencies
    # ここでssh
    - name: Start SSH via ngrok
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
          # After sign up on the https://ngrok.com
          # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

          # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
          # You can find this server region here: https://ngrok.com/docs#global-locations
        NGROK_REGION: jp

          # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    - name: Execute tests
      run: ./gradlew test
